# Generated by Django 6.0.4 on 2026-04-16 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_code', models.CharField(max_length=64, unique=True)),
                ('client_id', models.CharField(blank=True, max_length=64)),
                ('customer_request', models.TextField()),
                ('intent', models.CharField(choices=[('send_money', 'Send money'), ('get_airport_transfer', 'Airport transfer'), ('hire_service', 'Hire service'), ('verify_document', 'Verify document'), ('check_status', 'Check status')], max_length=32)),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('risk_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=16)),
                ('assigned_team', models.CharField(choices=[('FINANCE', 'Finance'), ('OPERATIONS', 'Operations'), ('LEGAL', 'Legal'), ('SUPPORT', 'Support')], default='SUPPORT', max_length=16)),
                ('ai_model', models.CharField(blank=True, max_length=128)),
                ('prompt_version', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_task_code', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=16)),
                ('new_status', models.CharField(max_length=16)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(default='system', max_length=64)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='assistant.task')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=16)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message_text', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.task')),
            ],
            options={
                'unique_together': {('task', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='TaskStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('step_text', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='assistant.task')),
            ],
            options={
                'ordering': ['step_order'],
                'unique_together': {('task', 'step_order')},
            },
        ),
    ]
